### ISSUE TITLE
Missing key lambda_sd_img

### ISSUE THREAD

**Issue by andytriboletti** [HeliosZhao/Animate124#1]
When I run the following test.sh I get this error:

    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key lambda_sd_img
    full_key: loss.lambda_sd_img
    object_type=dict

test.sh:
seed=0
gpu=0
exp_root_dir=outputs
DATA_DIR="panda-dance"
STATIC_PROMPT="a high resolution DSLR image of panda"
DYNAMIC_PROMPT="a panda is dancing"
CN_PROMPT="a <token> is dancing"

# --------- Stage 1 (Static Stage) --------- #
python launch.py --config custom/threestudio-animate124/configs/animate124-stage1.yaml --train --gpu $gpu \
data.image.image_path=custom/threestudio-animate124/load/${DATA_DIR}/_rgba.png \
system.prompt_processor.prompt="${STATIC_PROMPT}"

**Comment by HeliosZhao** [comment]
Hi, can you show the full traceback? I didn't see this error before

**Comment by andytriboletti** [comment]
I added some code in  custom/threestudio-animate124/configs/animate124-stage1.yaml

    lambda_sd_img: 0.01

don't know what it means. it got me past that error.

**Comment by andytriboletti** [comment]
add lambda_sd_img: 0.01 to yaml file

**Comment by gganjang** [comment]
Would you update .yaml file so that other people can save the time?
It took me a while to figure out the proper value for lambda_sd_img until I read this issue.
