### ISSUE TITLE
No video getting saved while running the run-cn.sh

### ISSUE THREAD

**Issue by mondalanindya** [HeliosZhao/Animate124#4]
Hi, thanks for your amazing work. I was wondering where the videos following semantic refinement are getting saved. Although run-dynamic.sh saves the videos in the specified location.

**Comment by HeliosZhao** [comment]
The result videos are saved after training [Here](https://github.com/HeliosZhao/Animate124/blob/d5469414eefb21525209374b4915ebf1e951ca4f/nerf/utils.py#L1191).
